buildscript {
    dependencies {
        classpath pl.springBoot
        classpath pl.docker
    }
}

group 'com.cgi.eoss.platform.core'
version '1.47.1-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'jacoco'
apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: 'org.springframework.boot'

dependencies {

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation project(':core:queues')
    implementation project(':core:processing:rpc')

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'io.kubernetes:client-java'
    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testImplementation project(path: ':core:queues', configuration: 'testClasses')
    testImplementation project(path: ':core:testutils', configuration: 'testClasses')

    testImplementation 'junit:junit'
    testImplementation 'io.fabric8:mockwebserver'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

jar {
    archiveBaseName = 'k8s-event-collector-core'
}

bootJar {
    archiveBaseName = 'k8s-event-collector-core'
    setArchiveClassifier('bin')
    launchScript()
}

docker {
    registryCredentials {
        url = project.hasProperty('DOCKER_REGISTRY_URL') ? project.property('DOCKER_REGISTRY_URL') : ''
        username = project.hasProperty('DOCKER_REGISTRY_USERNAME') ? project.property('DOCKER_REGISTRY_USERNAME') : ''
        password = project.hasProperty('DOCKER_REGISTRY_PASSWORD') ? project.property('DOCKER_REGISTRY_PASSWORD') : ''
        email = project.hasProperty('DOCKER_REGISTRY_EMAIL') ? project.property('DOCKER_REGISTRY_EMAIL') : ''
    }
}

import com.bmuschko.gradle.docker.tasks.image.*

task pullDockerImage(type: DockerPullImage) {
    if (project.hasProperty("DOCKER_REGISTRY_URL")) {
        image = project.getProperties().get("DOCKER_REGISTRY_URL") + "/" + "${project.group}/${jar.archiveBaseName.get()}:latest"
    }
    else{
        image = "${project.group}/${jar.archiveBaseName.get()}:latest"
    }
    onError { exception ->
        ;
    }
}

task buildDockerImage(type: DockerBuildImage) {
    dependsOn bootJar, pullDockerImage
    inputDir = file('.')
    if (project.hasProperty("DOCKER_REGISTRY_URL")) {
        images.add(project.getProperties().get("DOCKER_REGISTRY_URL") + "/" + "${project.group}/${jar.archiveBaseName.get()}:${project.version}")
        images.add(project.getProperties().get("DOCKER_REGISTRY_URL") + "/" + "${project.group}/${jar.archiveBaseName.get()}:latest")
        cacheFrom.add(project.getProperties().get("DOCKER_REGISTRY_URL") + "/" + "${project.group}/${jar.archiveBaseName.get()}:latest")
    }
    else{
        images.add("${project.group}/${jar.archiveBaseName.get()}:${project.version}")
        images.add("${project.group}/${jar.archiveBaseName.get()}:latest")
        cacheFrom.add("${project.group}/${jar.archiveBaseName.get()}:latest")
    }
    def base_image = project.getProperties().get("container.docker.baseImage") as String
    project.logger.info("Read {} from gradle.properties file as base image.", base_image)
    buildArgs = ['JAR_FILE': "target/libs/${jar.archiveBaseName.get()}-${project.version}-bin.jar",
                 'BASE_IMAGE': base_image]
}

task pushLatestDockerImage(type: DockerPushImage) {
    images = [project.getProperties().get("DOCKER_REGISTRY_URL") + "/" + "${project.group}/${jar.archiveBaseName.get()}:latest"]
}

task pushCurrentVersionDockerImage(type: DockerPushImage) {
    images = [project.getProperties().get("DOCKER_REGISTRY_URL") + "/" + "${project.group}/${jar.archiveBaseName.get()}:${project.version}"]
}

task pushDockerImage() {
    dependsOn pushLatestDockerImage, pushCurrentVersionDockerImage
}

jacoco {
    toolVersion = "0.8.9"
    reportsDir = file("$buildDir/jacoco")
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.enabled true
        csv.enabled false
    }
}

test {
    finalizedBy jacocoTestReport
}
