include 'core:processing:output-uploader'
include 'core:processing:input-downloader'
include 'core:processing:k8s-event-collector'
include 'core:processing:io'
include 'core:processing:rpc'
include 'core:processing:server:model'
include 'core:processing:server:persistence'
include 'core:processing:server:orchestrator'
include 'core:processing:server:app'
include 'core:processing:worker'
include 'core:queues'
include 'core:testutils'