application.title=Processing Server Core
server.port=8090
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/json,application/hal+json
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=6000MB
spring.servlet.multipart.max-request-size=6000MB
server.undertow.max-request-size=6000MB
server.undertow.max-http-post-size=6000MB
spring.main.allow-bean-definition-overriding=true

# APPLICATION CONFIGURATION

platform.server.app=processing-core


# Spring Persistence configuration
spring.flyway.enabled=true
spring.flyway.locations=db/migration/server-core/postgresql
spring.flyway.table=schema_version
spring.jpa.hibernate.ddl-auto=validate


# Database connection
#docker run --rm --name myPostgresEWA -p 5432:5432 -e POSTGRES_USER=postgresUser -e POSTGRES_PASSWORD=postgresPW -e POSTGRES_DB=platform_v2_eopaas_core postgres:18.4
spring.datasource.url=jdbc:postgresql://localhost/platform_v2_eopaas_core?stringtype=unspecified
spring.datasource.username=postgresUser
spring.datasource.password=postgresPW
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.autoCommit=false

# API module configuration
platform.api.basePath=/secure/api/v2.0


# Broker configuration
spring.activemq.broker-url=tcp://127.0.0.1:61616?wireFormat.maxInactivityDuration=0&jms.messagePrioritySupported=true
spring.activemq.user=admin
spring.activemq.password=admin