CREATE TABLE kubernetes_worker_jobs (
    job_id CHARACTER VARYING(255) PRIMARY KEY,
    end_time TIMESTAMP WITHOUT TIME ZONE,
    int_job_id CHARACTER VARYING(255) NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    status CHARACTER VARYING(255) NOT NULL CHECK (status IN
        ('STARTING', 'STARTED', 'COMPLETED', 'FAILED', 'ERROR', 'STOPPED', 'NOT_AVAILABLE')),
    group_id BIGINT,
    job_type CHARACTER VARYING(255) CHECK (job_type IN
        ('WORKFLOW', 'INTERACTIVE_APPLICATION'))
);