-- FS-TEP does not support schema migration when using HSQLDB
-- This 'migration' script is primarily to track the current DB schema for use in tests and test environments

-- Tables & Indexes
-- Compatibility mode with PostgreSQL for TEXT type
SET DATABASE SQL SYNTAX PGS TRUE;

CREATE TABLE users (
  uid  BIGINT IDENTITY PRIMARY KEY,
  mail CHARACTER VARYING(255),
  uuid CHARACTER VARYING(255),
  name CHARACTER VARYING(255)                 NOT NULL,
  role CHARACTER VARYING(255) DEFAULT 'GUEST' NOT NULL CHECK (role IN
                                                              ('GUEST', 'USER', 'EXPERT_USER', 'CONTENT_AUTHORITY', 'ADMIN'))
);
CREATE UNIQUE INDEX users_name_idx
  ON users (name);


CREATE TABLE services (
  id             BIGINT IDENTITY PRIMARY KEY,
  description    CHARACTER VARYING(255),
  docker_tag     CHARACTER VARYING(255),
  licence        CHARACTER VARYING(255) NOT NULL CHECK (licence IN ('OPEN', 'RESTRICTED')),
  name           CHARACTER VARYING(255) NOT NULL,
  service_descriptor TEXT,
  docker_build_info TEXT,
  required_resources TEXT,
  service_files_uri CHARACTER VARYING(255),
  strip_proxy_path BOOLEAN DEFAULT TRUE,
  external_uri   CHARACTER VARYING(255),
  status         CHARACTER VARYING(255) NOT NULL CHECK (status IN ('IN_DEVELOPMENT', 'AVAILABLE', 'DISABLED')),
  type           CHARACTER VARYING(255) NOT NULL CHECK (type IN ('PROCESSOR', 'BULK_PROCESSOR', 'APPLICATION', 'PARALLEL_PROCESSOR')),
  port CHARACTER VARYING(255),
  owner          BIGINT                 NOT NULL FOREIGN KEY REFERENCES users (uid),
  group_id       BIGINT,
  cwl_url        CHARACTER VARYING(255),
  cwl_document   TEXT
);
CREATE UNIQUE INDEX services_name_idx
  ON services (name);
CREATE INDEX services_owner_idx
  ON services (owner);

CREATE TABLE job_configs (
  id      BIGINT IDENTITY PRIMARY KEY,
  inputs  TEXT,
  parent  BIGINT,
  owner   BIGINT NOT NULL FOREIGN KEY REFERENCES users (uid),
  service BIGINT NOT NULL FOREIGN KEY REFERENCES services (id),
  systematic_parameter CHARACTER VARYING(255),
  label   CHARACTER VARYING(255),
  -- WARNING: No unique index on owner-service-inputs-parent-systematic_parameter as hsqldb 2.3.4 cannot index TEXT columns
  -- UNIQUE (owner, service, md5(inputs), parent, systematic_parameter)
);
CREATE INDEX job_configs_service_idx
  ON job_configs (service);
CREATE INDEX job_configs_owner_idx
  ON job_configs (owner);
CREATE INDEX job_configs_label_idx
  ON job_configs (label);

CREATE TABLE jobs (
  id         BIGINT IDENTITY PRIMARY KEY,
  end_time   TIMESTAMP WITHOUT TIME ZONE,
  ext_id     CHARACTER VARYING(255) NOT NULL,
  gui_url    CHARACTER VARYING(255),
  gui_endpoint    CHARACTER VARYING(255),
  is_parent  BOOLEAN DEFAULT FALSE,
  outputs    TEXT,
  stage      CHARACTER VARYING(255),
  start_time TIMESTAMP WITHOUT TIME ZONE,
  status     CHARACTER VARYING(255) NOT NULL CHECK (status IN
                                                    ('CREATED', 'RUNNING', 'COMPLETED', 'ERROR', 'CANCELLED', 'PENDING', 'WAITING', 'CONDITION_WAIT')),
  phase      CHARACTER VARYING(255) NOT NULL CHECK (phase IN
                                                    ('CREATED', 'DATA_FETCH', 'PROCESSING', 'OUTPUT_LIST')),
  job_config BIGINT                 NOT NULL FOREIGN KEY REFERENCES job_configs (id),
  owner      BIGINT                 NOT NULL FOREIGN KEY REFERENCES users (uid),
  parent_job_id BIGINT REFERENCES jobs (id),
  queue_position INTEGER,
  cost_quotation TEXT,
  worker_id CHARACTER VARYING(255),
  created TIMESTAMP WITH TIME ZONE,
  last_updated TIMESTAMP WITH TIME ZONE

);
CREATE UNIQUE INDEX jobs_ext_id_idx
  ON jobs (ext_id);
CREATE INDEX jobs_job_config_idx
  ON jobs (job_config);
CREATE INDEX jobs_owner_idx
  ON jobs (owner);

--Reference to parent in job config
ALTER TABLE job_configs ADD FOREIGN KEY (parent) REFERENCES jobs(id);

-- ServiceContextFile table
CREATE TABLE service_files (
  id         BIGINT IDENTITY PRIMARY KEY,
  service    BIGINT                NOT NULL FOREIGN KEY REFERENCES services (id),
  filename   CHARACTER VARYING(255),
  executable BOOLEAN DEFAULT FALSE NOT NULL,
  content    TEXT
);
CREATE UNIQUE INDEX service_files_filename_service_idx
  ON service_files (filename, service);
CREATE INDEX service_files_filename_idx
  ON service_files (filename);
CREATE INDEX service_files_service_idx
  ON service_files (service);

--User mounts
CREATE TABLE user_mounts (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 100 ) PRIMARY KEY,
  owner   BIGINT    NOT NULL REFERENCES users (uid),
  name 	  CHARACTER VARYING(255)	    NOT NULL,
  type 	  CHARACTER VARYING(255)	    NOT NULL,
  mount_path    CHARACTER VARYING(255)	NOT NULL
);

CREATE UNIQUE INDEX user_mount_name_owner_idx
  ON user_mounts (name);
CREATE INDEX user_mount_name_idx
  ON user_mounts (name);
CREATE INDEX user_mount_owner_idx
  ON user_mounts (owner);

--Mounts in services

CREATE TABLE services_mounts (
  service_id BIGINT NOT NULL FOREIGN KEY REFERENCES services (id),
  user_mount_id BIGINT NOT NULL FOREIGN KEY REFERENCES user_mounts (id),
  target_mount_path    CHARACTER VARYING(255)	NOT NULL
);

CREATE UNIQUE INDEX services_mounts_service_mount_idx
  ON services_mounts (service_id, user_mount_id);

